Create table benchmarking (
    Id NUMBER,
    Company_Name VARCHAR2 (250),
    Description VARCHAR2 (250),
    Commerce_type VARCHAR2 (250),
    Country VARCHAR2 (250),
    Department VARCHAR2 (250),
    City VARCHAR2 (250),
    Product VARCHAR2 (250),
    Product_type VARCHAR2 (250),
    price NUMBER,
    primary key (id)
);

BEGIN

INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (1, 'Sagal', 'Restaurant', 'Commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Guacamole x500g', 'Sauce', 16900);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (2, 'Jumbo', 'Supermarket', 'Commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Guacamole x250g', 'Sauce', 10990);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (3, 'Carulla', 'Supermarket', 'Commerce', 'Colombia', 'Caldas', 'Manizales', 'Guacamole x200g (Pietran)', 'Sauce', 10560);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (4, 'Carulla', 'Supermarket', 'Commerce', 'Colombia', 'Caldas', 'Manizales', 'Guacamole x228g (Bego)', 'Sauce', 12700);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (5, 'Carulla', 'Supermarket', 'Commerce', 'Colombia', 'Caldas', 'Manizales', 'Guacamole x400g (Chapatacon)', 'Sauce', 20000);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (6, 'Lauracate', 'Entrepreneurship', 'E-commerce', 'Colombia', 'Antioquia', 'Sabaneta', 'Guacamole x250g', 'Sauce', 13000);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (7, 'Lauracate', 'Entrepreneurship', 'E-commerce', 'Colombia', 'Antioquia', 'Sabaneta', 'Guacamole x500g', 'Sauce', 18000);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (8, 'Lauracate', 'Entrepreneurship', 'E-commerce', 'Colombia', 'Antioquia', 'Sabaneta', 'Guacamole x1000g', 'Sauce', 29000);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (9, 'Productos D Luis', 'Small business', 'E-commerce', 'Colombia', 'Valle del Cauca', 'Cali', 'Guacamole x250g', 'Sauce', 15500);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (10, 'Productos D Luis', 'Small business', 'E-commerce', 'Colombia', 'Valle del Cauca', 'Cali', 'Guacamole x500g', 'Sauce', 21900);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (11, 'Productos D Luis', 'Small business', 'E-commerce', 'Colombia', 'Valle del Cauca', 'Cali', 'Guacamole x1000g', 'Sauce', 32500);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (12, 'La despensa', 'Supermarket', 'E-commerce', 'Colombia', 'No se especifica', 'No se especifica', 'Guacamole artesanal x500g', 'Sauce', 13000);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (13, 'La despensa', 'Supermarket', 'E-commerce', 'Colombia', 'No se especifica', 'No se especifica', 'Guacamole artesanal x250g', 'Sauce', 8000);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (14, 'Distribuidora FP', 'Wholesaler', 'Commerce', 'Colombia', 'Antioquia', 'Bello', 'Guacamole x1000g (Rio grande)', 'Sauce', 11003);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (15, 'Mundo huevo', 'Wholesaler', 'Commerce', 'Colombia', 'Antioquia', 'Envigado', 'Guacamole x200g (Zafran)', 'Sauce', 5050);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (16, 'BGC Alimentos especiales', 'Small business', 'Commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Guacamole artesanal x1000g', 'Sauce', 20000);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (17, 'Surtifamiliar', 'Supermarket', 'Commerce', 'Colombia', 'Valle del Cauca', 'Cali', 'Guacamole x220g (K listo)', 'Sauce', 8900);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (18, 'Jumbo', 'Supermarket', 'Commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Manzana x6 unds', 'Fruit', 7984);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (19, 'Exito', 'Supermarket', 'Commerce', 'Colombia', 'Antioquia', 'Medellin', 'Manzana x800g (Frescampo)', 'Fruit', 9590);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (20, 'Plaza mercado', 'Supermarket', 'E-commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Manzana x1 und', 'Fruit', 2250);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (21, 'Olimpica', 'Supermarket', 'Commerce', 'Colombia', 'Caldas', 'Manizales', 'Manzana verde x1000g', 'Fruit', 15990);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (22, 'Carulla', 'Supermarket', 'Commerce', 'Colombia', 'Caldas', 'Manizales', 'Manzana verde x1 und', 'Fruit', 2400);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (23, 'La cesteria', 'Supermarket', 'E-commerce', 'Colombia', 'Antioquia', 'Medellin', 'Manzana verde x600g', 'Fruit', 11700);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (24, 'Supertiendas Comunal', 'Supermarket', 'Commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Manzana roja x1000g', 'Fruit', 14000);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (25, 'Mercaldas', 'Supermarket', 'Commerce', 'Colombia', 'Caldas', 'Manizales', 'Manzana verde x1 und', 'Fruit', 2050);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (26, 'Jumbo', 'Supermarket', 'Commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Jugo x500ml (Hit)', 'Juice', 2390);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (27, 'Olimpica', 'Supermarket', 'Commerce', 'Colombia', 'Caldas', 'Manizales', 'Jugo x1500ml (Del valle)', 'Juice', 2900);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (28, 'Tiendas metro', 'Supermarket', 'Commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Jugo x1000ml (Hit)', 'Juice', 3490);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (29, 'Merqueo', 'Supermarket', 'E-commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Jugo Nectar x1500ml (Pulp)', 'Juice', 5290);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (30, 'Jumbo', 'Supermarket', 'Commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Coca cola x1500ml', 'Soda', 5390);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (31, 'Exito', 'Supermarket', 'Commerce', 'Colombia', 'Antioquia', 'Medellin', 'Coca cola x1500ml', 'Soda', 5320);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (32, 'Exito', 'Supermarket', 'Commerce', 'Colombia', 'Antioquia', 'Medellin', 'Pony malta x1000ml', 'Soda', 3380);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (33, 'Jumbo', 'Supermarket', 'Commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Pony malta x1500ml', 'Soda', 4950);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (34, 'Olimpica', 'Supermarket', 'Commerce', 'Colombia', 'Caldas', 'Manizales', 'Pony malta x1000ml', 'Soda', 3500);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (35, 'Olimpica', 'Supermarket', 'Commerce', 'Colombia', 'Caldas', 'Manizales', 'Pony malta x2000ml', 'Soda', 6000);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (36, 'Carulla', 'Supermarket', 'Commerce', 'Colombia', 'Caldas', 'Manizales', 'Pony malta x200ml', 'Soda', 1400);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (37, 'Exito', 'Supermarket', 'Commerce', 'Colombia', 'Antioquia', 'Medellin', 'Leche entera x900 ml (Exito)', 'Milk', 3480);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (38, 'Jumbo', 'Supermarket', 'Commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Leche entera x1000ml (Colanta)', 'Milk', 4590);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (39, 'Tiendas metro', 'Supermarket', 'Commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Leche deslactosada x1100ml (Alqueria)', 'Milk', 6390);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (40, 'La vaquita', 'Small business', 'E-commerce', 'Colombia', 'Antioquia', 'Medellin', 'Leche entera x1000ml (Colanta)', 'Milk', 3990);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (41, 'La vaquita', 'Small business', 'E-commerce', 'Colombia', 'Antioquia', 'Medellin', 'Leche deslactosada x1000ml (Colanta)', 'Milk', 3990);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (42, 'Tiendas D1', 'Supermarket', 'Commerce', 'Colombia', 'Caldas', 'Manizales', 'Leche entera x200ml (Latti)', 'Milk', 1190);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (43, 'Tiendas D1', 'Supermarket', 'Commerce', 'Colombia', 'Caldas', 'Manizales', 'Leche entera x900ml (Latti)', 'Milk', 4690);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (44, 'Jumbo', 'Supermarket', 'Commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Leche entera x1100ml (Colanta)', 'Milk', 3990);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (45, 'Jumbo', 'Supermarket', 'Commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Galleta de vainilla x600g (Festival)', 'Cookies', 12390);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (46, 'Olimpica', 'Supermarket', 'Commerce', 'Colombia', 'Caldas', 'Manizales', 'Galleta salada x234g (Club social)', 'Cookies', 5567);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (47, 'Olimpica', 'Supermarket', 'Commerce', 'Colombia', 'Caldas', 'Manizales', 'Galleta integral x234g (Club social)', 'Cookies', 4880);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (48, 'Jumbo', 'Supermarket', 'Commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Aguacate Hass x500g', 'Fruit', 3990);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (49, 'Plaza mercado', 'Supermarket', 'E-commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Aguacate Hass x1000g', 'Fruit', 10700);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (50, 'La vaquita', 'Small business', 'E-commerce', 'Colombia', 'Antioquia', 'Medellin', 'Aguacate Hass x1000g', 'Fruit', 6690);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (51, 'Tiendas metro', 'Supermarket', 'Commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Aguacate Hass x500g', 'Fruit', 3940);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (52, 'Mercasur', 'Supermarket', 'Commerce', 'Colombia', 'Santander', 'Bucaramanga', 'Aguacate comun x1000g', 'Fruit', 9780);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (53, 'La cesteria', 'Supermarket', 'E-commerce', 'Colombia', 'Antioquia', 'Medellin', 'Aguacate papelillo verde x800g', 'Fruit', 8700);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (54, 'La cesteria', 'Supermarket', 'E-commerce', 'Colombia', 'Antioquia', 'Medellin', 'Aguacate Hass x220g', 'Fruit', 1600);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (55, 'Olimpica', 'Supermarket', 'Commerce', 'Colombia', 'Caldas', 'Manizales', 'Aguacate Hass x1000g', 'Fruit', 5990);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (56, 'Exito', 'Supermarket', 'Commerce', 'Colombia', 'Antioquia', 'Medellin', 'Aguacate x1 und', 'Fruit', 5000);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (57, 'Exito', 'Supermarket', 'Commerce', 'Colombia', 'Antioquia', 'Medellin', 'Fresas x500g', 'Berry', 7420);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (58, 'Jumbo', 'Supermarket', 'Commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Fresas x500g', 'Berry', 8990);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (59, 'Plaza mercado', 'Supermarket', 'E-commerce', 'Colombia', 'Cundinamarca', 'Bogota', 'Fresas x500g', 'Berry', 10700);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (60, 'Carulla', 'Supermarket', 'Commerce', 'Colombia', 'Caldas', 'Manizales', 'Fresas x500g', 'Fruit', 14400);
INSERT INTO benchmarking (Id, Company_Name, Description, Commerce_type, Country, Department, City, Product, Product_type, price) VALUES (61, 'Olimpica', 'Supermarket', 'Commerce', 'Colombia', 'Caldas', 'Manizales', 'Fresas x500g', 'Fruit', 6500);

END;
